name: Release

on: workflow_dispatch

jobs:
  build:
    name: ${{ matrix.platform.name }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: "Linux", os: ubuntu-22.04 }
          - { name: "Windows", os: windows-2022 }
          - { name: "MacOS", os: macos-12 }
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - if: ${{ matrix.platform.name == 'Linux' }}
        name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libx11-xcb-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build
